### PR TITLE
add issue templates

### PR DESCRIPTION
**Pull request by ocefpaf**
@mwengren, @MathewBiddle do you mind taking a look? This is a follow-up from our email communication recently.

xref.: https://github.com/ioos/glider-dac/issues/286#issuecomment-2025104156

### CODE REVIEW

**Comment by MathewBiddle** [comment]
These look great!

I'm curious if these will be added, _in addition_ to any other templates we might have in specific repositories? Or, if a repository has issue templates, it will only use those and not include these org wide ones. If it's _in addition_ we might want to change the programming language.

I'm thinking of https://github.com/ioos/bio_data_guide/issues/new/choose, specifically. 

If it's of interest, I drafted a bug_report template in https://github.com/ioos/compliance-checker-web/pull/126. I think they cover the same basis, but that one asks for more details (OS, browser, error logs, etc.)

**Comment by ocefpaf** [comment]
> I'm curious if these will be added, _in addition_ to any other templates we might have in specific repositories? Or, if a repository has issue templates, it will only use those and not include these org wide ones. If it's _in addition_ we might want to change the programming language.

It should use the project instead of the org wide ones. These are supposed to be very generic to cover the repos that did not add something specific.

> I'm thinking of https://github.com/ioos/bio_data_guide/issues/new/choose, specifically.
> 
> If it's of interest, I drafted a bug_report template in [ioos/compliance-checker-web#126](https://github.com/ioos/compliance-checker-web/pull/126). I think they cover the same basis, but that one asks for more details (OS, browser, error logs, etc.)

OS and error log is here, browser is specific to compliance-checker web. Note that I cast a wider net by saying " Errors, Traceback, and Logs." Nothing too specific, each project should have their own tweaked version if possible.

**Comment by MathewBiddle** [comment]
Okay. Looks good to me!

**Comment by mwengren** [comment]
Looks great, thanks Filipe!

**Pull request merged**
