### PR TITLE
add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ocefpaf**
This is based on Metpy's awesome Contributing guidelines. (Thanks @dopplershift and please let us know if/how we should mention any attribution here.)

@mwengren, @kbailey-noaa, and @MathewBiddle I do plan to edit this a further but it can be in future PRs if you want to merge this ASAP. If not, I'll get back to this in 1-2 weeks.

Here is what I want to change/improve:

- replace git with GitHub CLI commands
- add a section on docs that are unrelated to Software
- add something on how to run pre-commits before sending a PR

### CODE REVIEW

**Comment by MathewBiddle** [comment]
Thank you for starting this @ocefpaf! Is the idea that our org repositories would all reference this source CONTRIBUTING guide? Or, would we copy it and edit it for each repository? 

If it's the latter, I think it looks great!

**Comment by kbailey-noaa** [comment]
This looks great. I'd love to get this into the glider-dac repo as soon as possible.

**Comment by MathewBiddle** [comment]
Thanks for the changes @kbailey-noaa I'll merge

**Comment by ocefpaf** [comment]
> Thank you for starting this @ocefpaf! Is the idea that our org repositories would all reference this source CONTRIBUTING guide? Or, would we copy it and edit it for each repository?
> 
> If it's the latter, I think it looks great!

I think we could try both actually. Repositories that are mature and with mane devs should use this one as base and add their own details in their repository. However, new repositories, or those with few devs, could just link to this one (that is why I want to keep it as generic as possible) and/or just augment it with some notes in the README.

**Pull request merged**
